# Generated by Django 5.1.3 on 2024-12-31 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options'),
        ('store', 'XXXX_update_product_prices_descriptions'),
    ]

    operations = [
    ]
