# Generated by Django 5.1.3 on 2024-12-31 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_merge_20240101_xxxx'),
        ('store', '0003_merge_20241231_0442'),
    ]

    operations = [
    ]
