# Generated by Django 5.1.3 on 2024-12-31 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_merge_20241231_0443'),
    ]

    operations = [
    ]
