# Generated by Django 5.1.3 on 2024-12-31 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_update_prices_and_descriptions'),
        ('store', '0005_update_prices_and_descriptions'),
    ]

    operations = [
    ]
